### PR TITLE
adding marketplace faq

### PR DESCRIPTION
**Pull request by corey112358**

### CODE REVIEW

**Comment by corey112358** [comment]
@luciddreamz @jsvgoncalves please review

**Comment by jsvgoncalves** [comment]
@corey112358 clicking on `FAQ > Marketplace FAQs` leads to https://deploytestdevcenter-jgoncalv.rhcloud.com/en/external-services-faq.html, which is `404`, as well as https://deploytestdevcenter-jgoncalv.rhcloud.com/en/marketplace-faq.html

**Comment by luciddreamz** [comment]
Looks good.

On Thursday, February 18, 2016, João Gonçalves <notifications@github.com>
wrote:

> @corey112358 <https://github.com/corey112358> clicking on FAQ >
> Marketplace FAQs leads to
> https://deploytestdevcenter-jgoncalv.rhcloud.com/en/external-services-faq.html,
> which is 404, as well as
> https://deploytestdevcenter-jgoncalv.rhcloud.com/en/marketplace-faq.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/devcenter/pull/421#issuecomment-185973594>.
>


-- 
Jacob Lucky
jlucky@redhat.com | (919) 890-8540

**Comment by jsvgoncalves** [comment]
Fixed the problem with `.htaccess`, merging.

**Pull request merged**
