### PR TITLE
global: add travis with auto deployments

### PR DESCRIPTION
**Pull request by jsvgoncalves**
* Add the travis file with the build and deploy script, which has three main parts:

  1. Check if we want to deploy (if it's not a PR), and if we do, then set up the necessary ssh and git configurations, including fetching the production remote, so that we can commit the differences.

  2. Main build step with awestruct -u URL

  3. Checks again if we are deploying, and if so, create a commit with a somewhat nice message and push it to production.

* This commit also updates the used gems, and removes unused ones (e.g. nokogiri)

Signed-off-by: Joao Goncalves <jsvgoncalves@gmail.com>

### CODE REVIEW

**Comment by jsvgoncalves** [comment]
@developercorey @luciddreamz please review

**Comment by developercorey** [comment]
looks fine to me, @luciddreamz thoughts?

**Comment by developercorey** [comment]
@jsvgoncalves Instead of having id_rsa_deploy.enc in the repo, why don't we store the key we use for deployment as an environment variable in the travis-ci settings like we do for the settings to decrypt this key and use it?  Wouldn't that be safer? Less likely someone could download it and brute force it.

**Comment by jsvgoncalves** [comment]
@developercorey 

`data too large - consider using travis encrypt-file or travis env set`

**Comment by developercorey** [comment]
Ok, that makes sense

**Comment by developercorey** [comment]
Looks good to me unless @luciddreamz has any comments

**Comment by luciddreamz** [comment]
Looks good

**Pull request merged**
